##
# tasks for maintaining and deploying this middleman site
#
# relies on public key being set up for the user on the host

USER_NAME = "jimnist"
HOST_NAME = "jimnist.com"
SITE_NAME = "engine-earring.com"
SITE_DIR  = SITE_NAME + "/public"

desc "run dev server"
task :dev  do
  puts "dev serving"
  system('./scripts/dev_servers.sh')
end

desc "build site locally"
task :build  do
  puts "building site"
  system('middleman build --clean')
end

# TODO: test this
desc "deploy engine-earring.com to #{HOST_NAME}"
task :deploy => :build do
  cmd = "rsync -avrz build/ #{USER_NAME}@#{HOST_NAME}:#{SITE_DIR}"
  puts cmd
  system cmd
  puts "site deployed"
end
